---
name: Build and push dev image

on:
  pull_request:
    types: 
      - opened      # Triggers when the PR is first created
      - synchronize # Triggers whenever you push new commits to the PR branch
      - reopened    # Triggers if you close and reopen the PR
      - labeled
    paths:
      - 'docker/**'
      - 'version.json'
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  dev-build:
    if: success() && contains(github.event.pull_request.labels.*.name, 'Dev')
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - name: standard
            dockerfile: docker/Dockerfile
            platforms: linux/amd64,linux/arm/v7,linux/arm64

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Metadata ophalen is ook voor Dev essentieel voor het download-script
      - name: Get version
        id: version
        uses: notiz-dev/github-action-json-property@release
        with:
            path: 'version.json'
            prop_path: 'version'

      - name: Get channel
        id: channel
        uses: notiz-dev/github-action-json-property@release
        with:
            path: 'version.json'
            prop_path: 'channel'

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./docker/
          file: ${{ matrix.dockerfile }}
          platforms: ${{ matrix.platforms }}
          push: true
          # Hier voegen we de missende args weer toe
          build-args: |
            VERSION=${{ steps.version.outputs.prop }}
            CHANNEL=${{ steps.channel.outputs.prop }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            deconzcommunity/deconz:dev
            ghcr.io/${{ github.repository }}:dev
          labels: |
            org.opencontainers.image.vendor=${{ github.repository_owner }}
            org.opencontainers.image.revision=${{ github.sha }}
            development-build=true
